# 构建 VitePress 站点并将其部署到 GitHub Pages 的示例工作流程
#
name: Deploy VitePress site to Pages

on:
  # 在针对 `main` 分支的推送上运行。如果你
  # 使用 `master` 分支作为默认分支，请将其更改为 `master`
  push:
    branches: [main]

  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许同时进行一次部署，跳过正在运行和最新队列之间的运行队列
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Start Kroki server
      #   run: docker run -d -p 8000:8000 -e JAVA_OPTS="-Xmx512m" yuzutech/kroki
      # - name: test
      #   run: curl https://kroki.io/graphviz/svg --data-raw 'digraph G {Hello->World}'
      # - name: h
      #   run: |
      #     docker ps -a | grep kroki
      #     sleep 5
      # - name: test3
      #   run: curl -v http://localhost:8000
      # - name: test2
      #   run: curl http://localhost:8000/graphviz/svg --data-raw 'digraph G {Hell->World}'
        # run: sed -i 's|`https://kroki.io/${e}`|`https://localhost:8000/${e}`|g' node_modules/vitepress-plugin-diagrams/index.js
      # - name: replace2
      #   run: sed -i 's|`https://kroki.io/${e}`|`https://localhost:8000/${e}`|g' node_modules/vitepress-plugin-diagrams/index.cjs
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 如果未启用 lastUpdated，则不需要
      # - uses: pnpm/action-setup@v3 # 如果使用 pnpm，请取消此区域注释
      #   with:
      #     version: 9
      # - uses: oven-sh/setup-bun@v1 # 如果使用 Bun，请取消注释
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.4.1
          cache: npm # 或 pnpm / yarn
      # - name: replace
      #   run: ls -la node_modules/roughjs/bin/
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: npm ci # 或 pnpm install / yarn install / bun install
      - name: Build with VitePress
        run: npm run docs:build # 或 pnpm docs:build / yarn docs:build / bun run docs:build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  # 部署工作
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
